version: '3.8'

services:
  identity-db:
    image: postgres:15-alpine
    container_name: fitness-identity-db
    environment:
      POSTGRES_DB: fitness_identity
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
    volumes:
      - identity_data:/var/lib/postgresql/data
    networks:
      - fitness-network
    restart: unless-stopped

  identity-redis:
    image: redis:7-alpine
    container_name: fitness-identity-redis
    ports:
      - "6380:6379"
    networks:
      - fitness-network
    restart: unless-stopped

volumes:
  identity_data:

networks:
  fitness-network:
    driver: bridge